export enum IInternalRole {
  CHIEF = 'CHIEF',
  DIRECTOR = 'DIRECTORSHIP',
  MANAGEMENT = 'MANAGEMENT',
  HEADERSHIP = 'HEADERSHIP',
  LEADERSHIP = 'LEADERSHIP',
  DEVELOPER = 'DEVELOPER',
  OPERATOR = 'OPERATOR',
  DEFAULT = 'DEFAULT',
}
